[project]
name = "energy-meter-mqtt-to-prometheus"
version = "0.1.0"
description = "Translates Shelly Energy Monitor MQTT Messages to Prometheus Metrics "
requires-python = ">=3.10"
dependencies = [
]
